pipeline:
  build:
    image: maven:3-jdk-10-slim
    pull: true
    commands:
      - mvn package
    volumes:
      - /tmp/.m2:/root/.m2

  release:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    repo: danthonywalker/neon
    tags: latest
    build_args:
      - NEON_JAR=./target/neon.jar
    when:
      branch: master
